return function(T)
    T.test("example: github folder", function()
        local explanation =
            T.SpoonManager.from.github("muescha/SpoonRepo")
                .branch("main")
                .folder("Source/deepfolder")
                .withName("DeepFolder")
                .explain("install")

        T.assertEqual(explanation.definition.source.type, "github")
        T.assertEqual(explanation.definition.source.repository, "muescha/SpoonRepo")
        T.assertEqual(explanation.definition.source.revision_branch, "main")
        T.assertEqual(explanation.definition.target.selection_folder, "Source/deepfolder")
        T.assertEqual(explanation.definition.target.name_withName, "DeepFolder")
        T.assertEqual(explanation.command.from.type, "github-folder")
        T.assertEqual(explanation.command.from.archiveUrl, "https://github.com/muescha/SpoonRepo/archive/main.zip")
        T.assertEqual(explanation.command.to.name, "DeepFolder")
        T.assertMatchesJson("examples/github_folder.lua.explain.json", explanation)
    end)
end
